### PR TITLE
copy original .manifest files to output directory for pipeline 0.8

### PR DESCRIPTION
**Pull request by akihikokuroda**
# Changes
This PR is for https://github.com/tektoncd/experimental/issues/334

The `.MANIFEST` files in the `labels` and `comments` directories are copied into the directories under `output` directory for the pullrequest pipeline resource.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/experimental/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by akihikokuroda** [comment]
The unit test failure is by the js code coverage.

**Comment by akihikokuroda** [comment]
This PR has 2 commits.  one for 334 and the other for 340.

**Comment by a-roberts** [comment]
Testing this now, thanks @akihikokuroda 👍

**Comment by a-roberts** [comment]
Beautiful, I know there are two commits here but I want this change in and Aki's off on vacation

image

/lgtm
/approve

**Pull request merged**
