### PR TITLE
[octant-plugin] Remove octant-plugin

### PR DESCRIPTION
**Pull request by imjasonh**
I haven't made any changes in over a year, and I don't think the current plugin works against latest Octant now anyway. It might not even work against latest Tekton.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [n] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [y] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [y] Commit messages includes a project tag in the subject - e.g. [OCI], [hub], [results], [task-loops]

_See [the contribution guide](https://github.com/tektoncd/experimental/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by afrittoli — COMMENTED** [review]
/approve

**Comment by imjasonh** [comment]
/lifecycle frozen

Rebased

**Comment by imjasonh** [comment]
Thanks!

**Pull request merged**
