### PR TITLE
Use namespace in request body for creating secrets

### PR DESCRIPTION
**Pull request by a-roberts**
# Changes

For https://github.com/tektoncd/experimental/issues/69.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/experimental/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by a-roberts** [comment]
I'll be updating this shortly with the latest extension code (and hopefully the CLA problem goes away too)

**Comment by a-roberts** [comment]
@dibbles and I discussed this, I've added a test which is for if no namespace is provided in the request, the default gets used (so it is an allowed operation), removed a pointless logging message and updated the readme example.

**Comment by dibbles** [comment]
thanks @a-roberts 

/meow breaded

**Pull request merged**
