### PR TITLE
Refresh Tekton Python SDK

### PR DESCRIPTION
**Pull request by jinchihe**
# Changes

Refresh Tekton Python SDK

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Commit messages includes a project tag in the subject - e.g. [OCI], [hub], [results], [task-loops]

_See [the contribution guide](https://github.com/tektoncd/experimental/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by jinchihe** [comment]
We also need to update setup.py and example, but that's very strange, if I updated those files, then the two files will be conflicts. I will update later. Thanks.

**Review by afrittoli — COMMENTED** [review]
/approve

**Comment by afrittoli** [comment]
Thank you!

**Comment by jinchihe** [comment]
@afrittoli Thanks! would you please mark `/lgtm` since the label marked by @vincent-pli does not work.

**Pull request merged**
