### PR TITLE
Pipelines in Pipelines: Propagate Results

### PR DESCRIPTION
**Pull request by jerop**
# Changes

This project provides `Custom Task` / `Runs` that execute `PipelineRuns`,
which enables users to configure `Pipelines` in `Pipelines`

This change propagates `PipelineResults` from the `PipelineRun` to the
`Run` that created it - it maps `PipelineResults` to `RunResult`

Propagating `Results` ensures that they can be reused in the `Run` and
in subsequent `Tasks` if configured as a `Pipeline` in a `Pipeline`

Closes https://github.com/tektoncd/experimental/issues/732

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Commit messages includes a project tag in the subject - e.g. [OCI], [hub], [results], [task-loops]

_See [the contribution guide](https://github.com/tektoncd/experimental/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by jerop** [comment]
@bobcatfish thought you may be interested because of your pipeline in a pod custom task :)

**Review by afrittoli — COMMENTED** [review]
Nice, thank you!
/approve

**Review by sbwsg — APPROVED** [review]

**Pull request merged**
