### PR TITLE
[notifiers] GitHub App: Fix broken knative context and template.

### PR DESCRIPTION
**Pull request by wlynch**
# Changes

This changes fixes a few things that slipped by
https://github.com/tektoncd/experimental/pull/662 due to some bitrot.

- Updates Knative context code to disable leader election for the time
  being.
- Updates templates to handle in-progress TaskRuns where fields may
  be missing (e.g. CompletionTime, etc).

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [n/a] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Commit messages includes a project tag in the subject - e.g. [OCI], [hub], [results], [task-loops]

_See [the contribution guide](https://github.com/tektoncd/experimental/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by dibyom — APPROVED** [review]

**Comment by dibyom** [comment]
@wlynch you might want to add an OWNERS file for notifiers so that we don't need a root experimental OWNER for approvals

**Comment by wlynch** [comment]
> @wlynch you might want to add an OWNERS file for notifiers so that we don't need a root experimental OWNER for approvals

https://github.com/tektoncd/experimental/pull/747

**Pull request merged**
