### PR TITLE
Automatically use the generated hash for your service yaml

### PR DESCRIPTION
**Pull request by a-roberts**
It's irritating to constantly change the hash after changing web code, so under this PR make it no longer required = though you do need yq

### CODE REVIEW

**Comment by a-roberts** [comment]
@mnuttall fixed the yq troubles 👀

**Comment by mnuttall** [comment]
The `yq` check is working, but changes to the javascript aren't causing new files to appear in cmd/extension/kodata when ./build-it.sh or `nom run build_ko` are run : (

**Comment by a-roberts** [comment]
@mnuttall the weird thing is you didn't get a new build after clearly modifying some JavaScript

```
(base) adams-mbp:webhooks-extension aroberts$ ls -la cmd/extension/kodata/
total 224
drwxr-xr-x  3 aroberts  staff      96 29 Jan 17:09 .
drwxr-xr-x  4 aroberts  staff     128 29 Jan 17:09 ..
-rw-r--r--  1 aroberts  staff  111564 29 Jan 17:13 extension.b3c58eb7.js

(base) adams-mbp:webhooks-extension aroberts$ code src/WebhookApp.js 

(base) adams-mbp:webhooks-extension aroberts$ ls cmd/extension/kodata/
extension.b3c58eb7.js

(base) adams-mbp:webhooks-extension aroberts$ npm run build_ko

> extension@0.0.1 build_ko /Users/aroberts/go/src/github.com/tektoncd/experimental/webhooks-extension
> ./build-it.sh ./cmd/extension/kodata
... omitted some junk ...

removed 1 package and audited 891165 packages in 35.007s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

src/WebhookApp.js → ./cmd/extension/kodata...
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
created ./cmd/extension/kodata in 16.1s
... more omitting ...

+ react@16.12.0
added 1 package and audited 891174 packages in 43.449s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
Thinking the newest file (your build?) is extension.3919ee7c.js
Thinking the hash to use is 3919ee7c
yqing...
apiVersion: v1
kind: Service
metadata:
  name: webhooks-extension
  namespace: tekton-pipelines
  labels:
    app: webhooks-extension
    tekton-dashboard-extension: "true"
  annotations:
    tekton-dashboard-display-name: Webhooks
    tekton-dashboard-endpoints: webhooks.web
    tekton-dashboard-bundle-location: web/extension.3919ee7c.js
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: webhooks-extension
Done!
(base) adams-mbp:webhooks-extension aroberts$ ls -la cmd/extension/kodata/
total 448
drwxr-xr-x  4 aroberts  staff     128 29 Jan 17:16 .
drwxr-xr-x  4 aroberts  staff     128 29 Jan 17:09 ..
-rw-r--r--  1 aroberts  staff  111606 29 Jan 17:16 extension.3919ee7c.js
-rw-r--r--  1 aroberts  staff  111564 29 Jan 17:13 extension.b3c58eb7.js
```

I modified WebhookApp.js and added a <h1> in the return

**Comment by a-roberts** [comment]
/test tekton-experimental-unit-tests

👼

**Comment by a-roberts** [comment]
Awkward moment when it just isn't building the bundle now

**Comment by mnuttall** [comment]
Works for me locally now - just waiting for the tests to pass :-/

**Comment by a-roberts** [comment]
@mnuttall tests passed 🍈

**Pull request merged**
