### PR TITLE
fix tab indexing & replace tooltips to hoverable ones

### PR DESCRIPTION
**Pull request by carlos-logro**
issue: #66 

#Changes

Fixed the tab indexing by initializing all the values to 0 & leaving the browser do the logical ordering and surprisinly works. But its worth mentioning that I had to cheat a little with plain javascript when trying to skip the disabled components because for some reason their child elements still had `tabIndex set to 0` and was interrupting the order. I also changed the tooltips to "hoverable" ones but only to those that are in the main page and not the modals because for some reason they were not being outputted correctly. Lastly, I had to update the test with some errors regarding the `window.toScroll` & create a new test file to bypass the `'initialFocus' did not return a node` error. 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

### CODE REVIEW

**Comment by dibbles** [comment]
@carlos-logro do you have a code formatter running? Most of the modifications are unrelated to the actually functional change and I wondered whether we should have the discussion about having a code formatter checked in, that everyone should apply to their dev environment - otherwise we will just keep seeing files changing back and forth as different people use different formatters.

Looks like you have unit test failures to fix up - but in general it looks fine.

**Comment by carlos-logro** [comment]
@dibbles @AlanGreene  manage to remove the formatting. As for the failed test I don't know why does error messages are showing up because I didn't touch none of those files.

**Comment by jessm12** [comment]
I've just given this another test and look over and all looks good, behaves as expected, just the hash conflicts to resolve and I'd say it's good to go 😄

**Comment by carlos-logro** [comment]
@a-roberts @jessm12 ready for merge :)

**Comment by a-roberts** [comment]
Yep, thanks Carlos (assuming tests continue to pass 😅)

/approve
/lgtm

**Pull request merged**
