### PR TITLE
Use zap as logger for webhook extension

### PR DESCRIPTION
**Pull request by a-roberts**
# Changes

Use a logger that gives us more granularity than `log` such as `Infof`, `Debugf`, `Errorf` as well as `Fatalf`.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
N/A

- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/experimental/blob/master/CONTRIBUTING.md)
for more details._

__Not to be merged please until @dibbles' incoming change is in - we've had some fun with merges!__

### CODE REVIEW

**Comment by a-roberts** [comment]
@ncskier FYI, can you please take a look?

**Comment by a-roberts** [comment]
@ncskier ah, thanks Brandon, what a terrible mistake! Have a look at the statements I have added though and by the time you're up tomorrow I'll have fixed that, thanks 😅

**Comment by ncskier** [comment]
No worries. Will do 😄

**Comment by a-roberts** [comment]
Fixed, as though nothing ever happened...

For sanity's sake I've ran:
- ` docker build -f cmd/extension/Dockerfile_test .` and 
- `docker build -f cmd/sink/Dockerfile_test .`

No failures

**Pull request merged**
