### PR TITLE
generators: add a LICENSE and bump plumbing

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

Trying to fix the experimental CI.

- Adds a LICENSE file to `generators` and other projects that are missing it
- Disable `task-loops` CI (doesn't work anymore)
- Update plumbing to most recent versions
- `gofmt` on go files

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [ ] Commit messages includes a project tag in the subject - e.g. [OCI], [hub], [results], [task-loops]

_See [the contribution guide](https://github.com/tektoncd/experimental/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by vdemeester** [comment]
cc @jerop @afrittoli

**Review by wlynch — COMMENTED** [review]
FWIW, I don't think we strictly need licenses here as long as they're apache 2, since the top level repo already defines a license?

**Review by dibyom — APPROVED** [review]
/lgtm

**Comment by vdemeester** [comment]
> FWIW, I don't think we strictly need licenses here as long as they're apache 2, since the top level repo already defines a license?

Yes I tend to agree, but `go-license` didn't as it treats each go project (defined by a `go.mod`) separately, and thus was failing for most of them.

**Pull request merged**
