### PR TITLE
Fix install url in pipelines-in-pipelines README

### PR DESCRIPTION
**Pull request by jonashackt**
fixes https://github.com/tektoncd/experimental/issues/817

# Changes

Replace authenticated nightly release url with the pulblic access url (as also in https://github.com/tektoncd/experimental/pull/816).

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [ ] Commit messages includes a project tag in the subject - e.g. [OCI], [hub], [results], [task-loops]

_See [the contribution guide](https://github.com/tektoncd/experimental/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by jerop** [comment]
thanks @jonashackt 

/ok-to-test

**Comment by jerop** [comment]
@jonashackt could you please sign the CLA?

**Comment by jonashackt** [comment]
> @jonashackt could you please sign the CLA?

Yeah sure, done 🙃

**Review by dibyom — APPROVED** [review]

**Review by dibyom — COMMENTED** [review]
/lgtm

**Pull request merged**
