### PR TITLE
Generate Tekton Pipeline Python SDK

### PR DESCRIPTION
**Pull request by jinchihe**
# Changes
Note the PR is separate from the PR: https://github.com/tektoncd/pipeline/pull/3081 you can get more from there

The PR is going to generate Tekton Pipeline Python SDK. Python SDK is very import for end user.

### Design and implements:
1. Use openapi-gen to generate OpenAPI specification from Go struct definition.  (The part is kept in `tektoncd/pipeline` repo https://github.com/tektoncd/pipeline/pull/3081)
2. And then generate the swagger file from the OpenAPI specification.  (The part is kept in tektoncd/pipeline repo tektoncd/pipeline#3081)
3. Use swagger-codegen to generate the python SDK for the python object models (basic on some Kubernetes Python models). 
4. Then we need to develop some Client API such as create, update, delete to maintain Tekton objects, for this, we can use the Kubernetes CRD Python APIs.
5. Update Readme file (generated) and the docs that linked to Kubernetes Python APIs, and some manually works.
6. After finished, we can publish the SDK to [Pypi](https://pypi.org/project/tekton-pipeline/) so that user can easy to install and use the SDK.

See details in the generate script: https://github.com/tektoncd/experimental/blob/b0ac9b0e37a3ba850395831582c7a0f32e50b009/sdk/hack/README.md

 ### Examples:
```python
from tekton import TektonClient
from tekton import V1beta1TaskRun
from tekton import V1beta1TaskRunSpec
from tekton import V1beta1TaskSpec
from tekton import V1beta1Step
from kubernetes import client

taskrun = V1beta1TaskRun(
    api_version='tekton.dev/v1beta1',
    kind='TaskRun',
    metadata=client.V1ObjectMeta(name='sdk-sample-taskrun'),
    spec=V1beta1TaskRunSpec(
        task_spec=V1beta1TaskSpec(
            steps=[V1beta1Step(name='default',
                            image='ubuntu',
                            script='sleep 30;echo "This is a sdk demo.')]
        )))

tekton_client = TektonClient()
tekton_client.create(taskrun, namespace='default')
```

See detailed examples of taskrun here: https://github.com/tektoncd/experimental/blob/7f25f4c46dc6f30548cde7089e1c7c180e482311/sdk/python/examples/taskrun.ipynb

See detailed Readme and related docs in the PR: https://github.com/tektoncd/experimental/blob/7f25f4c46dc6f30548cde7089e1c7c180e482311/sdk/python/README.md

### What's the next:
This is a init SDK generation, lots of things need to do, such as make more Client APIs manually, in this PR, I just finish basic apis... Thanks.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/experimental/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by jinchihe** [comment]
Hey Reviewers, the PR is ready for review now. Thanks.

/cc @vdemeester

**Comment by jinchihe** [comment]
@vdemeester Any more comments? I think that's ready. Thanks.

**Review by afrittoli — COMMENTED** [review]
Thank you for this!
I think the first should be to merge it in, and we can then take it from there.
If you are part of the tekton org, you may want to add yourself and OWNER to this folder.
/approve

**Comment by jinchihe** [comment]
I will take a look the CI issue and fix that ASAP . Thanks.

**Comment by jinchihe** [comment]
Seems the CI test is passed now. Thanks!

**Pull request merged**
