### PR TITLE
plgen: tekton DSL based on Dockerfile

### PR DESCRIPTION
**Pull request by gireeshpunathil**
# Changes

`plgen` is a tekton pipeline generator from simple verbs that align to `Dockerfile` syntax

The objective of plgen is to provide a high level DSL for generating tekton pipeline from simple verbs that align to Dockerfile syntax, hide the complex kubernetes semantics, and thereby improve the overall user experience with tekton pipelines.

 - the Dockerfile verbs `ARG, FROM, RUN, LABEL, ENV, MOUNT`, and `USER` are used in the generator without losing much of their original meaning
 - as we are not using any Dockerfile parser, we are free to deviate when situation demands it
 - my idea of covering more scenarios is to wait for some end user feedback, set the semantics straight, and then specialize on those, however I am open to suggestions

thanks to those who provided vital feedback - @ImJasonH @brandonkal @mnuttall @vdemeester

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/experimental/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by gireeshpunathil** [comment]
for those who want to view the plgen in action without compiling and running it:

A targz pipeline can be encoded as below:

```Dockerfile
LABEL targz
USER core
FROM ubuntu
ARG input=http://github.com/foo/archive.tar.gz
ENV foo=bar
RUN tar xzvf $input
RUN cat source/file.txt
```


which gets (currently) translated to:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: core
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin
subjects:
- kind: ServiceAccount
  name: core
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
items:
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: input
  spec:
    type: git
    params:
    - name: resource0
      value: http://github.com/foo/archive.tar.gz
kind: List
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: l-txt-pipeline
spec:
  resources:
  - name: input
    type: git
  tasks:
  - name: l-txt
    taskRef:
      name: l-txt-task
      kind: ""
    resources:
      inputs:
      - name: input
        resource: input
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: l-txt-task
spec:
  inputs:
    resources:
    - name: input
      type: git
  outputs: {}
  steps:
  - name: targz
    image: ubuntu
    env:
    - name: foo
      value: bar
    command:
    - /bin/bash
    args:
    - -c
    - tar xzvf http://github.com/foo/archive.tar.gz
    - -c
    - cat source/file.txt
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: l-txt-pipeline-run
spec:
  serviceAccount: core
  timeout: 1h0m0s
  pipelineRef:
    name: l-txt-pipeline
  trigger:
    type: manual
  resources:
  - name: input
    resourceref:
      name: input
---
```

**Comment by gireeshpunathil** [comment]
bump. what it takes to help move this forward? thanks.

**Comment by gireeshpunathil** [comment]
nearing 3 months with no review - not a great way to motivate new contributors! let me know what is the blocker here:

 - too much code to review? I can present it in one of the forums you suggest
 - lacking a description / flow? I have attempted to sketch one, but pls suggest if needs more
 - lacking review time? I am happy to wait, but pls state so!

**Comment by vdemeester** [comment]
Hey @gireeshpunathil, sorry for the loooong wait :sweat: 

>     * too much code to review? I can present it in one of the forums you suggest
>     * lacking a description / flow? I have attempted to sketch one, but pls suggest if needs more
>     * lacking review time? I am happy to wait, but pls state so!

It's definitely a lack of review time (and focusing on other subject, like the soon-to-be beta api of tektoncd/pipeline, …).

On the "high-level" approach, I wonder how much using `Dockerfile` as a DSL for `Task`/`Pipeline` make sense :

- `Dockerfile` is really limited in what it can do : there is no graph involved, and there is some command in it (like `USER`) that are weirdly translatable in a `Task`.
- `Dockerfile` are meant to generate an `oci-image` in the end (and most of the time are written this way) and this assumption is very limited to the translation into `Task` (your experiment doesn't seem to generate images).


There is a few weird thing in the generated yamls, that I don't think work

-  the generated `PipelineResource` would validate, the param `resource0` is not supported by a `PipelineResource` of type `git`
```
apiVersion: v1
items:
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: input
  spec:
    type: git
    params:
    - name: resource0
      value: http://github.com/foo/archive.tar.gz
```

- `/bin/bash -c … -c …` only execute the first (as far as I know)
```
    command:
    - /bin/bash
    args:
    - -c
    - tar xzvf http://github.com/foo/archive.tar.gz
    - -c
    - cat source/file.txt
```

**Comment by gireeshpunathil** [comment]
@vdemeester  - thanks for the review!

> Dockerfile is really limited in what it can do : there is no graph involved, and there is some command in it (like USER) that are weirdly translatable in a Task.

 - my premise is that pipeline tasks are imperative in nature, that fits the Dockerfile philosphy
 - I kind of agree, the existing Dockerfile verbs are limited, but `plgen` parser is extensible to fit pipeline needs
 - it allows to define and standardize new verbs that are most natural for the pipeline tasks.
 - pipeline tasks themselves are not too complex, and can be seen as well scoped in a minimal set of vocabulary


> Dockerfile are meant to generate an oci-image in the end (and most of the time are written this way) and this assumption is very limited to the translation into Task (your experiment doesn't seem to generate images).

 - of course, we are not using the syntax to create images, instead for defining pipelines
 - Dockerfile is an analogy, meant for fast ramp up and easy representation
 - the analogy should become evident to any consumer on the first use
 - software programming domain is filled with such analogies: `print`, `thread`, `kill`, `gc`, `throw`, `native` ... no user will associate these keywords with their original meaning, beyond the first use IMO.


> There is a few weird thing in the generated yamls, that I don't think work

 - agreed, I can get back to my branch, familiarize with the code (it has been some time) and fix those; but given that there are design level questions that needs to be ratified; I will delay the bug fixing until then.


In general, I appeal to contemplate this approach as independent from `yaml` semantics as possible - In my experience, the problem of comparing with an established baseline is that:

 - the gaps of comparing entity from the baseline gets highlighted more
 - any novelty in the comparing entity gets masked off, as those don't appear for comparison, because those are missing in the baseline.

**Pull request closed without merging**
