### PR TITLE
[workflows] Add presubmit tests

### PR DESCRIPTION
**Pull request by lbernick**
# Changes

This commit adds presubmit tests for the workflows project, using
default test runners from plumbing scripts.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Commit messages includes a project tag in the subject - e.g. [OCI], [hub], [results], [task-loops]

_See [the contribution guide](https://github.com/tektoncd/experimental/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by lbernick** [comment]
Related: https://github.com/tektoncd/experimental/issues/916

**Comment by dibyom** [comment]
(The test failure is from a different project)

**Comment by lbernick** [comment]
I think the test failure is actually in workflows-- there's something wrong with the codegen scripts that's resulting in an incorrect go.mod, need to debug. The same thing is happening for https://github.com/tektoncd/experimental/pull/917

**Review by khrm — COMMENTED** [review]
/lgtm

**Pull request merged**
