### PR TITLE
Results: Read test DB schema from file.

### PR DESCRIPTION
**Pull request by wlynch**
# Changes

This ensures that the same schema is used for real and test servers.

Also includes a few minor cleanups in setupTestDB:
- Split `t.Cleanup` into 2 Cleanups in order to ensure that Cleanups occur
  even if there is a partial failure.
- Use `t.Helper` in setupTestDB helper func.
- Remove usused variable from setupTestDB.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/experimental/blob/master/CONTRIBUTING.md)
for more details._

/assign @yuege01

### CODE REVIEW

**Comment by ImJasonH** [comment]
I'd love to get https://github.com/tektoncd/experimental/pull/539 merged, then make sure this works with that change. Does that sound okay to you?

**Comment by wlynch** [comment]
> I'd love to get #539 merged, then make sure this works with that change. Does that sound okay to you?

Yup! Fine by me.

/hold

**Pull request merged**
