### PR TITLE
Add instructions for new projects + fix links 📝

### PR DESCRIPTION
**Pull request by bobcatfish**
# Changes

This isn't an exhaustive list but wanted to at least get it started!
I completely missed the presubmit-tests.sh update and @jerop caught it
for me but wanted to document this for folks in the future.

To be thorough we should also add more about how to add all the files
you need for your project (e.g. even that presubmit script assumes
certain other scripts are in the project folder)

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [n/a] Commit messages includes a project tag in the subject - e.g. [OCI], [hub], [results], [task-loops]

_See [the contribution guide](https://github.com/tektoncd/experimental/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by bobcatfish** [comment]
really need to introduce some retries into this thing XD

image



/test pull-tekton-experimental-build-tests

**Review by jerop — COMMENTED** [review]
thanks for documenting this @bobcatfish!

/lgtm

**Comment by bobcatfish** [comment]
Looks like the linter found a legit broken links - had nothing to do with my change but oh well 🤣  Added another commit to this PR:

    Fix links to apache licenses 🔗

    Not sure why these were trying to link to some kubernetes copy of the
    license but that seems to be gone now, so instead just linking to the
    existing license in the folder.

    The markdown linter is a bit to vigorous and instead of just checking
    the files I was changing decided to lint all the markdown files. Oh
    well, that's one way to get it fixed I guess :D

**Comment by bobcatfish** [comment]
Looks like there were some more legit broken links (though why they are being caught NOW is a bit of a mystery) - and it looks like some of the loops integration tests might be flakey 🤞  that they will pass this time

**Comment by bobcatfish** [comment]
YAASSSS

image

**Review by jerop — APPROVED** [review]

**Review by imjasonh — APPROVED** [review]

**Pull request merged**
