### PR TITLE
[results] Add v1alpha2 API surface.

### PR DESCRIPTION
**Pull request by wlynch**
# Changes

This spec is based on the TEP proposal: https://github.com/tektoncd/community/blob/master/teps/0021-results-api.md

Introduces Record subresources in favor of Events. Since this is a
breaking change from the initial API, rev to v1alpha2.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [n/a] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Commit messages includes a project tag in the subject - e.g. [OCI], [hub], [results], [task-loops]

_See [the contribution guide](https://github.com/tektoncd/experimental/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by dibyom** [comment]
/approve

One question: Given that the API is experimental/alpha, do we need to bump up the apiversion to v1alpha2? Our API compatibility allows for breaking changes in alpha APIs

**Comment by wlynch** [comment]
> /approve
> 
> One question: Given that the API is experimental/alpha, do we need to bump up the apiversion to v1alpha2? Our API compatibility allows for breaking changes in alpha APIs

Follow up off-thread - while we don't need to bump the version, this makes it easier to update the API in pieces without needing to rewrite both client/server pieces. The plan is to remove the v1alpha1 API ASAP once v1alpha2 is ready.

**Pull request merged**
