### PR TITLE
Hub:Deprecates Hub `ui` and redirect to upstream Hub

### PR DESCRIPTION
**Pull request by PuneetPunamiya**
Signed-off-by: Puneet Punamiya <ppunamiy@redhat.com>

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Commit messages includes a project tag in the subject - e.g. [OCI], [hub], [results], [task-loops]

_See [the contribution guide](https://github.com/tektoncd/experimental/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by SM43** [comment]
Why don't we just delete the whole `hub` directory?

**Review by vdemeester — APPROVED** [review]
/meow
/cc @afrittoli @bobcatfish @ImJasonH

**Review by piyush-garg — APPROVED** [review]

**Comment by bobcatfish** [comment]
Echoing @SM43 's question, but I'm assuming the answer is that we do plan to do that in the long run?

/lgtm

**Comment by piyush-garg** [comment]
Yes @bobcatfish Plan is to redirect for now if someone coming here and later we can delete cc @tektoncd/hub-maintainers 

Thanks for merging

**Pull request merged**
