### PR TITLE
[pipeline/trusted-resources] Refact/clean error on return vals

### PR DESCRIPTION
**Pull request by austinzhao-go**
# Changes

Refactor the helper func `getSignerFromFile` to remove the unused `error` return val
 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing) - not user facing as for refactoring work
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Commit messages includes a project tag in the subject - e.g. [OCI], [hub], [results], [task-loops]

_See [the contribution guide](https://github.com/tektoncd/experimental/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by wlynch — COMMENTED** [review]
/lgtm

I think this looks good, but waiting until the base commit is submitted before approving. (alternatively if you want to cherry pick the commit that works for me too)

**Comment by austinzhao-go** [comment]
/unhold 

as https://github.com/tektoncd/experimental/pull/886 was merged

**Review by Yongxuanzhang — APPROVED** [review]
Thanks a lot @austinzhao-go and @wlynch !! 😄

**Pull request merged**
