### PR TITLE
visible close button in inline notification

### PR DESCRIPTION
**Pull request by carlos-logro**
issue: #68 

# Changes
for some reason the close button had `visibility: hidden`. Changing its value made it appear.
Other changes were because of the prettier rules.

### CODE REVIEW

**Comment by AlanGreene** [comment]
The close button on inline notifications was hidden via the core dashboard styles due to an issue with an earlier version of the Carbon components. My latest PR to update the Carbon version addresses this: https://github.com/tektoncd/dashboard/pull/281/files#diff-2bb8937103ebd9b3252030a0ed786351L32

**Comment by carlos-logro** [comment]
great so this PR can be closed then?

**Comment by AlanGreene** [comment]
yes it can be closed, or if you want to keep the formatting changes you could just remove the button visibility change

**Comment by dibbles** [comment]
@carlos-logro what did you want to do with this PR - close it?

**Comment by carlos-logro** [comment]
yeah forgot to close it...

**Pull request closed without merging**
