### PR TITLE
add limitations

### PR DESCRIPTION
**Pull request by akihikokuroda**
# Changes

Add limitations in the DEVELOPMENT.md

This is for the issue https://github.com/tektoncd/experimental/issues/188.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/experimental/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by akihikokuroda** [comment]
I updated the statement.

**Comment by mnuttall** [comment]
> The webhooks API is expecting only https url. The webhook is using Knative github event source to setup the webhook in the github. It requires the access token. The `SSH authentication (Git)` is not supported by the webhooks extension.  The users should use the `Basic authentication (Git)` with the secret containing the access token.  For details, refer to [Authentication](https://github.com/tektoncd/pipeline/blob/master/docs/auth.md).

Aki, thank you for the update. I think that the text could still be improved: it's not clear what we're trying to say. Since @dacleyra opened the issue in the first place, do you think that you could work with him to rewrite this into a form that would satisfy him, please?

**Comment by a-roberts** [comment]
@akihikokuroda agreed on the need for a reword, fyi we now have https://github.com/tektoncd/experimental/blob/master/webhooks-extension/docs/Limitations.md as well so this would be better suited in there

**Comment by a-roberts** [comment]
This is superseded/invalidated by our new limitations with the work we're doing around Triggers now so we're good to close this one (I see in this PR we mention knative still and https endpoints for example), thank you anyway @akihikokuroda 😸

**Pull request closed without merging**
