### PR TITLE
Install webhooks extension on openshift to openshift-pipelines, matching Dashboard

### LINKED ISSUE #522: Webhooks extension on OpenShift should also use openshift-pipelines
It does for the dashboard on OpenShift and the extension has to be in the same namespace, so make it so

### PR DESCRIPTION
**Pull request by a-roberts**
Closes #522

One liner that saves me replacing tekton-pipelines everywhere on OpenShift

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/experimental/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by Megan-Wright** [comment]
@a-roberts I'm getting 
```
(base) Megans-MacBook-Pro:webhooks-extension megan.wright@ibm.com$ kustomize build overlays/openshift-development | ko apply -f -
Error: accumulating resources: recursed accumulation of path '/Users/megan.wright@ibm.com/go/src/github.com/tektoncd/experimental/webhooks-extension/overlays/openshift-all': no matches for OriginalId rbac.authorization.k8s.io_v1_Role|openshift-pipelines|tekton-webhooks-extension-minimal; no matches for CurrentId rbac.authorization.k8s.io_v1_Role|openshift-pipelines|tekton-webhooks-extension-minimal; failed to find unique target for patch rbac.authorization.k8s.io_v1_Role|tekton-webhooks-extension-minimal
error: no objects passed to apply
2020/05/20 15:08:28 error executing 'kubectl apply': exit status 1
``` 
with this change...

**Comment by eddycharly** [comment]
`kustomize build overlays/openshift-all` runs fine here

**Comment by Megan-Wright** [comment]
works perfectly
/lgtm

**Comment by a-roberts** [comment]
@AlanGreene should be an easy one, looking for an approve please 😸

**Pull request merged**
