### PR TITLE
Make webhooks work with triggers master

### PR DESCRIPTION
**Pull request by CarolynMabbott**
# Changes

Changes to make webhooks work with master of triggers which should be triggers 0.6.0 release 

Thanks to @ncskier and @Megan-Wright for helping 😸 
# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/experimental/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by Megan-Wright** [comment]
Tested this out and everything seems to be working with master of triggers.. worth noting that this will mean that webhooks won't support triggers 0.5.0 anymore unlike the dashboard, but looking good otherwise 😸 
/lgtm

**Comment by a-roberts** [comment]
Changes look good, what about https://github.com/tektoncd/experimental/blob/c74ba9eadbeb61a8c2a00dbd5ca5d8a979e4165c/webhooks-extension/test/config.sh#L6 ? Unused or doesn't matter? Not seeing in changed files but maybe it's not run.

And we don't clearly call out the Triggers supported version anywhere, might be worth adding that into the main readme.

**Comment by CarolynMabbott** [comment]
> Changes look good, what about
> 
> https://github.com/tektoncd/experimental/blob/c74ba9eadbeb61a8c2a00dbd5ca5d8a979e4165c/webhooks-extension/test/config.sh#L6
> 
> ? Unused or doesn't matter? Not seeing in changed files but maybe it's not run.
> And we don't clearly call out the Triggers supported version anywhere, might be worth adding that into the main readme.

Completely forgot about the install script in the test folder 

Yeah I'll update pipelines to 0.13.2
I cant update triggers to master because it gets releases so can put it at 0.6 and hope they bring the release out soon?
I'll add in the README about compatibility

**Comment by anneqm** [comment]
Since this is breaking change for webhooks from Triggers release 0.5 to 0.6,  wondering if we need a dot release on current dashboard and webhooks extension for pipelines range (Pipelines 0.11, 0.12, and 0.13. ) at the triggers support 0.4 and 0.5 version?

**Comment by a-roberts** [comment]
> Since this is breaking change for webhooks from Triggers release 0.5 to 0.6, wondering if we need a dot release on current dashboard and webhooks extension for pipelines range (Pipelines 0.11, 0.12, and 0.13. ) at the triggers support 0.4 and 0.5 version?

That'd make sense but we've already got the change in for Triggers 0.6 in master, which was a breaking change, on this week's working group call https://docs.google.com/document/d/1bG4mbjycmFtIBezA6AJoQvaB4-v3874dhX7n-DhGAx0/edit# we discussed the 0.7.1 release and agreed that's going to be the 0.6 release and potentially the improved installer

**Pull request merged**
