### PR TITLE
[cel] install from nightly release

### PR DESCRIPTION
**Pull request by jerop**
# Changes

Users have been installing `ko` and using it to build and install the
controller on their clusters

We now have a Cron Job that builds a nightly release
https://github.com/tektoncd/plumbing/tree/main/tekton/cronjobs/dogfooding/releases/cel-nightly

This change adds documentation for installing from the nightly release

/kind documentation

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Commit messages includes a project tag in the subject - e.g. [OCI], [hub], [results], [task-loops]

_See [the contribution guide](https://github.com/tektoncd/experimental/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by afrittoli** [comment]
The failure is on the webhook extension:
```
go: cannot find main module, but found Gopkg.lock in /home/prow/go/src/github.com/tektoncd/experimental/webhooks-extension
	to create a module there, run:
	go mod init
unit_tests returning 
===========================
==== UNIT TESTS FAILED ====
===========================
```

So I think something is broken in the checks for which project is affected by a change, we should not be running unit tests from project other than CEL on this PR.

**Comment by jerop** [comment]
thanks @afrittoli -- it's all passing now that webhook extension was deleted in https://github.com/tektoncd/experimental/pull/751

**Review by afrittoli — COMMENTED** [review]
/approve
/lgtm

**Pull request merged**
