### PR TITLE
Add details on (lack of) code standards in experimental

### PR DESCRIPTION
**Pull request by lbernick**
# Changes
This commit clarifies the expectations that contributors and users
can have for code in this repo. Projects are encouraged
to define their own expectations, but in general, expectations are
lower than for other repos in the tektoncd org.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- n/a Commit messages includes a project tag in the subject - e.g. [OCI], [hub], [results], [task-loops]

_See [the contribution guide](https://github.com/tektoncd/experimental/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by lbernick** [comment]
@afrittoli @dibyom I've chatted with you about this-- lmk what you think
@jerop you may also be interested

**Review by vdemeester — APPROVED** [review]

**Review by jerop — APPROVED** [review]

**Comment by lbernick** [comment]
added a LICENSE to /generators, let's see if that fixes the build tests

**Comment by afrittoli** [comment]
The only log that is left in terms of licenses is all warnings, so I don't think this is causing failures now:

```
-----------------------------------------
---- Checking for forbidden licenses ----
-----------------------------------------
W0705 13:50:14.250012   11207 library.go:86] "github.com/modern-go/reflect2" contains non-Go code that can't be inspected for further dependencies:
/home/prow/go/pkg/mod/github.com/modern-go/reflect2@v1.0.1/reflect2_amd64.s
/home/prow/go/pkg/mod/github.com/modern-go/reflect2@v1.0.1/relfect2_mips64x.s
/home/prow/go/pkg/mod/github.com/modern-go/reflect2@v1.0.1/relfect2_mipsx.s
/home/prow/go/pkg/mod/github.com/modern-go/reflect2@v1.0.1/relfect2_ppc64x.s
W0705 13:50:15.915009   11207 library.go:86] "golang.org/x/sys/unix" contains non-Go code that can't be inspected for further dependencies:
/home/prow/go/pkg/mod/golang.org/x/sys@v0.0.0-20200327173247-9dae0f8f5775/unix/asm_linux_amd64.s
```


My guess is that these errors are the issue:
```
----------------------------------------------
---- Checking links in the markdown files ----
----------------------------------------------
README.md
	ERROR	https://developer.github.com/webhooks/securing/#setting-your-secret-token
		Forbidden (HTTP error 403)
	ERROR	https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token#creating-a-token
		Forbidden (HTTP error 403)
--------------------------------
```

**Comment by afrittoli** [comment]
This thread is related to the 403 issues: https://github.com/github-community/community/discussions/14773

I was able to reproduce the issue using curl, it expects some HTTP headers that are not sent by the linter

**Comment by afrittoli** [comment]
ok, this should fix things https://github.com/tektoncd/experimental/pull/891

**Comment by afrittoli** [comment]
Heh, fix one error, get the next 😓 
I'm going to just merge this one 🙏

**Pull request merged**
