### PR TITLE
replace api calls with dashboard's redux selectors & actions

### PR DESCRIPTION
**Pull request by carlos-logro**
issue: #137 

# Changes
removed & replaced the api calls for getting namespaces, service accounts and pipelines with the redux selectors & actions that were passed as props to the extension component. Also updated all necessary tests. 

Its worth mentioning that the api call to get webhook secrets was left because at the moment the getSecrets action did not return the secrets created for webhooks.

### CODE REVIEW

**Comment by AlanGreene** [comment]
Please break this PR down into more easily reviewed chunks. Some suggestions:
- migrate a subset (even 1) of the APIs instead of doing them all in one go
- keep large whitespace / formatting changes separate from functional changes where possible
- avoid introducing unnecessary complexity in mock data (e.g. most of the resource metadata fields are irrelevant), it distracts from the actual tests / functionality of interest.

I'm also seeing a lot of inconsistency in use of single vs. double quotes, and other issues that should be picked up / fixed by the linter.

**Comment by carlos-logro** [comment]
@AlanGreene 
Divided the PR so in this first one I included the update to the namespace API call only and each modified test. Also, at the moment the prettier & ESLint rules are not on in this repo, that's why they are not being picked up.

**Comment by AlanGreene** [comment]
@carlos-logro conflict on the hash again. It might be worth investing (separately) in removing the need to specify that at all since virtually any front end change causes conflicts.

Otherwise looks good 👍

**Comment by carlos-logro** [comment]
@AlanGreene 
re-hashed. 

& definitely, a workaround must be done with the hash to make it simpler merge PRs.

**Pull request merged**
